/*初始化*/
INSERT INTO TEAM_NAV.NAV_ROLE(ID, ROLE_NAME, UPDATE_TIME)
SELECT '1', '管理员', NOW() WHERE NOT EXISTS (SELECT 1 FROM TEAM_NAV.NAV_ROLE WHERE ID='1');

INSERT INTO TEAM_NAV.NAV_ROLE_USER(ID, ROLE_ID, USER_ID)
SELECT '1', '1', '1' WHERE NOT EXISTS (SELECT 1 FROM TEAM_NAV.NAV_ROLE_USER WHERE ID='1');
